name: Test Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install dvc pandas

      - name: Check DVC version
        run: dvc --version

      - name: Pull data
        run: dvc pull --no-exec
        env:
          DVC_PASSWORD: ${{ secrets.DVC_PASSWORD }}

      - name: Run test
        run: |
          python test_pipeline.py
